/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./../components/Chat.vue')['default']
    ChatHistory: typeof import('./../components/ChatHistory.vue')['default']
    ChatMessage: typeof import('./../components/ChatMessage.vue')['default']
    ChatSend: typeof import('./../components/ChatSend.vue')['default']
    ChatShow: typeof import('./../components/ChatShow.vue')['default']
    CounterComp: typeof import('./../components/CounterComp.vue')['default']
    InputComponent: typeof import('./../components/InputComponent.vue')['default']
    NavLayout: typeof import('./../components/NavLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTerms: typeof import('./../components/SearchTerms.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    SwitchComponent: typeof import('./../components/SwitchComponent.vue')['default']
    TabLayout: typeof import('./../components/TabLayout.vue')['default']
    Tooltip: typeof import('./../components/Tooltip.vue')['default']
    WordCloudComponent: typeof import('./../components/WordCloudComponent.vue')['default']
  }
}
